name: ddx_trainer
description: "Fitness application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  flutter_secure_storage: ^9.2.2
  get_it: ^7.7.0
  dio: ^5.4.3+1
  cupertino_radio_choice: ^1.0.2
  intl: ^0.19.0
  badges: ^3.1.2
  image_picker: ^0.8.4+3
  permission_handler: ^10.3.0
  table_calendar: ^3.1.2
  numberpicker: ^2.1.2
  file_picker: ^8.0.5
  video_player: ^2.8.7
  record: ^4.4.4
  just_audio: ^0.9.38


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/

flutter_icons:
  android: true